### ISSUE TITLE
シミュレータ環境でのLiDAR（距離データ）の扱い方をしらべる

### ISSUE THREAD

**Issue by seigot** [seigot/burger_war#4]
> Lider（距離データ）の扱い方

**Comment by seigot** [comment]
TOPICは以下が該当する

```
ubuntu@ubuntu:~/catkin_ws/src/burger_war$ rostopic list
/red_bot/scan
```

データ構造は以下のようだ

```
ubuntu@ubuntu:~/catkin_ws/src/burger_war$ rosmsg show sensor_msgs/LaserScan
std_msgs/Header header
  uint32 seq
  time stamp
  string frame_id
float32 angle_min
float32 angle_max
float32 angle_increment
float32 time_increment
float32 scan_time
float32 range_min
float32 range_max
float32[] ranges
float32[] intensities
```

**Comment by seigot** [comment]
シミュレーション環境で実際にechoすると下記のようなデータがはいっている

```
ubuntu@ubuntu:~/catkin_ws/src/burger_war$ rostopic echo /red_bot/scan 
header: 
  seq: 157
  stamp: 
    secs: 381
    nsecs: 645000000
  frame_id: "red_bot/base_scan"
angle_min: 0.0
angle_max: 6.28318977356
angle_increment: 0.0175019223243
time_increment: 0.0
scan_time: 0.0
range_min: 0.119999997318
range_max: 3.5
ranges: [0.8960722088813782, 0.9125479459762573, 0.9245286583900452, 2.186138153076172, 2.2128288745880127, 2.2322838306427, 2.2156121730804443, 2.227569341659546, 2.2519850730895996, 2.2711844444274902, 2.2783138751983643, 2.313544511795044, 1.841178059577942, 1.824204921722412, 1.853145956993103, 1.817563533782959, 1.8013384342193604, 1.7781621217727661, 1.8863239288330078, 2.460437536239624, 2.4907050132751465, 2.5228922367095947, 1.099940538406372, 1.1094928979873657, 1.1011921167373657, 1.112632155418396, 1.1169131994247437, 1.0840319395065308, 1.1077460050582886, 1.0835645198822021, 1.0862946510314941, 1.0981873273849487, 1.1100834608078003, 1.0890401601791382, 1.0860745906829834, 1.1056791543960571, 1.106557846069336, 1.0994707345962524, 1.0970603227615356, 1.0938355922698975, 2.5898935794830322, 2.5603513717651367, 2.517348527908325, 2.475860834121704, 2.446784734725952, 1.798182487487793, 1.7714052200317383, 1.7773571014404297, 1.798685073852539, 1.8110464811325073, 1.8026410341262817, 1.828927755355835, 2.2716047763824463, 2.246683120727539, 2.227921724319458, 2.2125918865203857, 2.199471950531006, 2.1810693740844727, 0.8923484683036804, 0.8514797687530518, 0.8113256096839905, 0.7994101047515869, 0.7678442001342773, 0.7561449408531189, 0.7733159065246582, 0.8002755641937256, 0.7806841731071472, 0.8026705980300903, 0.7993617653846741, 0.8104678392410278, 0.8158922791481018, 0.8380659818649292, 0.8772246837615967, 0.8635807633399963, 2.046964406967163, 2.039747714996338, 2.041173219680786, 2.0350265502929688, 2.036857843399048, 2.037278890609741, 2.03499174118042, 2.038628339767456, 2.0494608879089355, 2.0581464767456055, 2.0396158695220947, 1.8906350135803223, 1.647775650024414, 1.4727320671081543, 1.3116446733474731, 1.2194308042526245, 1.1023718118667603, 1.023723840713501, 0.9491581916809082, 0.9092921614646912, 0.854424774646759, 0.7946314215660095, 0.7547363042831421, 0.7200011610984802, 0.6873560547828674, 0.6419212222099304, 0.6342391967773438, 0.5908501148223877, 0.5745936632156372, 0.537261962890625, 0.5208291411399841, 0.5097184181213379, 0.4922848641872406, 0.46585115790367126, 0.46246007084846497, 0.4580260217189789, 0.4483742117881775, 0.4338301718235016, 0.4155714511871338, 0.40340548753738403, 0.41431188583374023, 0.3738664388656616, 0.3757089674472809, 0.376981258392334, 0.3843629062175751, 0.3467058837413788, 0.3466379940509796, 0.34034228324890137, 0.3303903043270111, 0.3326023817062378, 0.32264482975006104, 0.3149714171886444, 0.31740471720695496, 0.30321627855300903, 0.3115716874599457, 0.3121759295463562, 0.3032899796962738, 0.30529049038887024, 0.3083796501159668, 0.2874258756637573, 0.29225993156433105, 0.2838677167892456, 0.27512598037719727, 0.2550986409187317, 0.2762172818183899, 0.2792397737503052, 0.2836710512638092, 0.27250418066978455, 0.2516593933105469, 0.26534077525138855, 0.24695232510566711, 0.26276150345802307, 0.24562469124794006, 0.24639511108398438, 0.26557424664497375, 0.25677070021629333, 0.24128656089305878, 0.24389022588729858, 0.24188043177127838, 0.2502776086330414, 0.2623377740383148, 0.22788169980049133, 0.23765988647937775, 0.24219092726707458, 0.24981538951396942, 0.23480276763439178, 0.2410425841808319, 0.2511886954307556, 0.23183555901050568, 0.23427973687648773, 0.22329308092594147, 0.2373303920030594, 0.21506375074386597, 0.23160797357559204, 0.2456057220697403, 0.24919767677783966, 0.21611520648002625, 0.24466721713542938, 0.2433328628540039, 0.24386553466320038, 0.22237122058868408, 0.21871277689933777, 0.24593143165111542, 0.23393911123275757, 0.23919515311717987, 0.2627972960472107, 0.2488948255777359, 0.2326815277338028, 0.2580384314060211, 0.25749671459198, 0.2531561553478241, 0.24725811183452606, 0.25176432728767395, 0.26215457916259766, 0.24017469584941864, 0.24864430725574493, 0.2473469376564026, 0.2686251103878021, 0.2657710909843445, 0.24709053337574005, 0.26474645733833313, 0.28147679567337036, 0.2693708837032318, 0.26225745677948, 0.27531155943870544, 0.285847932100296, 0.2862556278705597, 0.28566214442253113, 0.290039986371994, 0.30185744166374207, 0.2946683466434479, 0.28404298424720764, 0.30418694019317627, 0.3001340329647064, 0.3130185604095459, 0.3049703538417816, 0.30980345606803894, 0.31970295310020447, 0.34023433923721313, 0.34003278613090515, 0.3620362877845764, 0.3247111141681671, 0.3465406000614166, 0.37487804889678955, 0.36490756273269653, 0.37393704056739807, 0.4115365445613861, 0.39098528027534485, 0.36635079979896545, 0.396639347076416, 0.3784661293029785, 0.3678723871707916, 0.3692190647125244, 0.34874120354652405, 0.3524690270423889, 0.34956327080726624, 0.3734111189842224, 0.3603503406047821, 0.35053715109825134, 0.35541218519210815, 0.3440401256084442, 0.3375210165977478, 0.3373444080352783, 0.33512526750564575, 0.3397528827190399, 0.31998884677886963, 0.3500830829143524, 0.323482871055603, 0.330323189496994, 0.33639800548553467, 0.3248605728149414, 0.3115274906158447, 0.3072023391723633, 0.3258756995201111, 0.32201671600341797, 0.33655932545661926, 0.31189459562301636, 0.3061904311180115, 0.3016466796398163, 0.3120386302471161, 0.3240106701850891, 0.3272641897201538, 0.3157459795475006, 0.3311520218849182, 0.32296156883239746, 0.30940642952919006, 0.32893842458724976, 0.31657445430755615, 0.3173098862171173, 0.31359151005744934, 0.3043491840362549, 0.2928955852985382, 0.32437336444854736, 0.33396515250205994, 0.3299337327480316, 0.3226088881492615, 0.30584603548049927, 0.33444300293922424, 0.334450364112854, 0.3410961329936981, 0.33831968903541565, 0.33723872900009155, 0.3366486728191376, 0.34191977977752686, 0.3479363024234772, 0.34222254157066345, 0.32339322566986084, 0.3359886109828949, 0.3263520896434784, 0.3617652952671051, 0.3456731140613556, 0.36019620299339294, 0.37106016278266907, 0.3574516475200653, 0.3679487109184265, 0.3547991216182709, 0.385028213262558, 0.3756134808063507, 0.37587910890579224, 0.38934391736984253, 0.4126010239124298, 0.4059582054615021, 0.4140692353248596, 0.4049597382545471, 0.4210893511772156, 0.42626699805259705, 0.4424521327018738, 0.4458690583705902, 0.442306250333786, 0.4567148685455322, 0.4571987986564636, 0.47261133790016174, 0.48358288407325745, 0.47514334321022034, 0.48201411962509155, 0.5063819885253906, 0.5165317058563232, 0.5380959510803223, 0.5628038048744202, 0.5641008615493774, 0.5653746724128723, 0.5909844636917114, 0.6112937331199646, 0.624056339263916, 0.6533758640289307, 0.683333158493042, 0.689327597618103, 0.7081397175788879, 0.7330085635185242, 0.7765134572982788, 0.8087628483772278, 0.8244089484214783, 0.8847562670707703, 0.9124800562858582, 0.9569626450538635, 0.997489333152771, 1.0731526613235474, 1.1381925344467163, 1.211515188217163, 1.2928396463394165, 1.3667348623275757, 1.5132362842559814, 1.6300071477890015, 1.7912007570266724, 1.9879977703094482, 2.1297218799591064, 2.1244301795959473, 2.129741668701172, 2.1108555793762207, 2.137842893600464, 2.11201810836792, 2.11246395111084, 2.100938081741333, 0.9461910128593445, 0.9312981367111206, 0.9150421023368835, 0.8812090158462524, 0.8791664838790894, 0.8744199275970459, 0.8626013994216919, 0.849084198474884, 0.8283886313438416, 0.8092427849769592, 0.8557983040809631, 0.8626816272735596, 0.9012268781661987]
intensities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.5140183567598747e-35, 1.5140183567598747e-35, 1.5140183567598747e-35, 1.5140183567598747e-35, 1.5140183567598747e-35, 1.5140183567598747e-35, 1.5140183567598747e-35, 0.0, 0.0, 0.0, 1.6498935651004306e-35, 1.6498935651004306e-35, 1.6498935651004306e-35, 1.6498935651004306e-35, 1.6498935651004306e-35, 1.6498935651004306e-35, 1.6498935651004306e-35, 1.6498935651004306e-35, 1.6498935651004306e-35, 1.6498935651004306e-35, 1.6498935651004306e-35, 1.6498935651004306e-35, 1.6498935651004306e-35, 1.6498935651004306e-35, 1.6498935651004306e-35, 1.6498935651004306e-35, 1.6498935651004306e-35, 1.6498935651004306e-35, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 9.528829557408756e-44, 9.528829557408756e-44, 9.528829557408756e-44, 9.528829557408756e-44, 9.528829557408756e-44, 9.528829557408756e-44, 9.528829557408756e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 8.96831017167883e-44, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
```
