### ISSUE TITLE
自律走行経路の安定化

### ISSUE THREAD

**Issue by seigot** [seigot/burger_war#9]
走行中にぐるぐる、壁にぶつかってスタックする問題解決に向けて安定化を図る

**Comment by seigot** [comment]
以下を調べる

```
LEVEL 2,3
raucha
rabbits
```

**Comment by seigot** [comment]
```
rauchaとのnavigationパラメータの差分
```

```
● costmap_common_params_burger.yaml 微妙にパラメータがチューニングされている
robot_radius: 0.03
inflation_radius: 0.5
cost_scaling_factor: 10.0

● dwa_local_planner_params_burger.yaml 沢山パラメータチューニングされている
# The velocity when robot is moving in a straight line
  max_trans_vel:  0.22
  min_trans_vel:  0.1
  # min_trans_vel:  0.1

  max_rot_vel: 2.75
  min_rot_vel: 0.05
  # min_rot_vel: 1.37

  acc_lim_x: 2.5
  acc_lim_y: 0.0
  acc_lim_theta: 3.2

# Goal Tolerance Parametes
  xy_goal_tolerance: 0.15
  # xy_goal_tolerance: 0.05
  yaw_goal_tolerance: 0.34
  # yaw_goal_tolerance: 0.17
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 1.5
  # sim_time: 0.5
  vx_samples: 20
  vy_samples: 0
  vth_samples: 40
  controller_frequency: 10.0

# Trajectory Scoring Parameters
  # path_distance_bias: 100.0
  path_distance_bias: 700.0
  # path_distance_bias: 150.0
  # path_distance_bias: 32.0
  goal_distance_bias: 20.0
  # goal_distance_bias: 5.0
  occdist_scale: 0.02
  forward_point_distance: 0.1
  # forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

●global_costmap_params.yaml 微妙にパラメータがチューニングされている
resolution: 0.025

●local_costmap_params.yaml  微妙にパラメータがチューニングされている
width: 5
height: 5
resolution: 0.025s
# resolution: 0.05

●move_base_params.yamlに以下パラメータが記載されている。これは何？
recovery_behavior_enabled: true
recovery_behaviors:
    - name: 'aggressive_reset'
      type: 'clear_costmap_recovery/ClearCostmapRecovery'
    - name: 'clearing_rotation1'
      type: 'rotate_recovery/RotateRecovery'

aggressive_reset:
    reset_distance: 0.05
    layer_names: ["obstacle_layer"]

```
